name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.10.1"]
        target: [Homework01AnswerTests]  # Add more targets as needed

    runs-on: ${{ matrix.os }}

    # strategy:
    #   matrix:
    #     target: [Homework01AnswerTests, Homework02AnswerTests, Homework03AnswerTests]  # Add more targets as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}  # Specify the Swift version you need

    - name: Build and test
      run: swift test --filter ${{ matrix.target }}
