name: Swift

on: [push]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }} for ${{ matrix.target.name }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.10"]
        target:
          - name: Homework01AnswerTests
            path: Homeworks/Homework1
          # - name: Homework02AnswerTests
          #   path: Homeworks/Homework2
          # - name: Homework03AnswerTests
          #   path: Homeworks/Homework3

    runs-on: ${{ matrix.os }}

    # strategy:
    #   matrix:
    #     target: [Homework01AnswerTests, Homework02AnswerTests, Homework03AnswerTests]  # Add more targets as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}  # Specify the Swift version you need

    # - name: Change to homework directory
    #   run: cd ${{ matrix.target.path }}

    - name: Build and test
      run: | 
        cd ${{ matrix.target.path }}
        swift test --filter ${{ matrix.target.name }}
